---
app_deploy_image: nginxinc/nginx-unprivileged:1.29-alpine@sha256:0c79d56aee561a1d81c63f00eee5fb5fe29279560cdc55e91425133104c7fbe6

app_deploy_container_name: petclinic
app_deploy_port: 8080
app_deploy_container_port: 8080

app_deploy_service_name: petclinic-app
app_deploy_run_script: /usr/local/bin/petclinic-app-run
app_deploy_state_dir: /opt/petclinic

app_deploy_placeholder: true
app_deploy_placeholder_root: /opt/petclinic/placeholder

app_deploy_gcloud_bin: /snap/bin/gcloud

app_deploy_project: "{{ gcp_project }}"

app_deploy_db_config_secret: dev-db-app-config
app_deploy_db_password_secret: dev-db-app-password

app_deploy_fetch_db_config: true
app_deploy_fetch_db_password: "{{ not (app_deploy_placeholder | bool) }}"

app_deploy_spring_profile: mysql

app_deploy_env: {}

app_deploy_registry: europe-west3-docker.pkg.dev
